// Renderer produces an html string from a tree of tokens (generated by the lexer)
var Renderer = {};

Renderer.render = function(tree){
    // If the argument passed is not an array (so, a string), return it immediately
    if(!Array.isArray(tree)) return tree;

    // Elese, the argument is an array of tokens
    // Iterate over each one, pushing it to the string
    var rendered = "";
    for(var i = 0; i < tree.length; i++){
        var token = tree[i];
        // To get the contents, call the function recursively
        var contents = Renderer.render(token.content);

        rendered += `${TOKEN_DATA[token.type].html(contents)}`;
    };
    return rendered;
};